### ISSUE TITLE
If the Netherite Elytra is equipped in the curious tab, the game will crash

### ISSUE THREAD

**Issue by Craftjakob** [DrunkBlood/Netherite-Elytra#16]
If the Netherite Elytra is equipped in the curious tab, the game will crash:
This version: 1.0.0-1.19-curios

The Crash Report:
> net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: **fallFlyTicks**
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:227) ~[fmlcore-1.19-41.1.0.jar%23199!/:?] {}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.getPrivateValue(ObfuscationReflectionHelper.java:72) ~[fmlcore-1.19-41.1.0.jar%23199!/:?] {}
	at drunkblood.netheriteelytra.item.NetheriteElytraItem.curioTick(NetheriteElytraItem.java:127) ~[netherelytra-1.0.0-1.19-curios.jar%23184!/:1.0.0-1.19-curios] {re:classloading}
	at top.theillusivec4.curios.api.type.capability.ICurio.curioTick(ICurio.java:63) ~[curios-forge-1.19.1-5.1.0.5.jar%23160!/:1.19.1-5.1.0.5] {re:classloading,re:mixin}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$20(CuriosEventHandler.java:497) ~[curios-forge-1.19.1-5.1.0.5.jar%23160!/:1.19.1-5.1.0.5] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19-41.1.0-universal.jar%23203!/:?] {re:mixin,re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.lambda$tick$25(CuriosEventHandler.java:497) ~[curios-forge-1.19.1-5.1.0.5.jar%23160!/:1.19.1-5.1.0.5] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19-41.1.0-universal.jar%23203!/:?] {re:mixin,re:classloading}
	at top.theillusivec4.curios.common.event.CuriosEventHandler.tick(CuriosEventHandler.java:476) ~[curios-forge-1.19.1-5.1.0.5.jar%23160!/:1.19.1-5.1.0.5] {re:classloading}
	at top.theillusivec4.curios.common.event.__CuriosEventHandler_tick_LivingTickEvent.invoke(.dynamic) ~[curios-forge-1.19.1-5.1.0.5.jar%23160!/:1.19.1-5.1.0.5] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.19-41.1.0-universal.jar%23203!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:242) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:286) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:197) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:MixinLocalPlayer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:335) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.ClientLevel.lambda$tickEntities$4(ClientLevel.java:312) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:308) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1761) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1047) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23198!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.1.0.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NoSuchFieldException: fallFlyTicks
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:221) ~[fmlcore-1.19-41.1.0.jar%23199!/:?] {}
	... 39 more

**Comment by Blugori** [comment]
It also happened for 1.18.2 : 
https://crashy.net/FnjoZcz7vDfznDrctIbb
but I'm using a lot of mods, maybe I'm wrong

**Comment by Blugori** [comment]
My bad, I forgot to install the "elytra slot" mod... this fixed the issue for me !
https://www.curseforge.com/minecraft/mc-mods/elytra-slot
